# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e344082b6b27cc0cd3377bcae100809b01acb9bb3ba1ec6b3746eec15d5a5f7569d2fa8436dfe735da69b4d6579133f8c5a8e590c483d92fbc33c08f8c788a92

test:
  secret_key_base: 5e70548c2fd028e86cbf18afc73290e8109fa34ca0dd5a7e4c4601f7db75d5b8e40a314fa22f5a5e7f498a6730229231b980a43f88dca0f48cb27e7ea86b35e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
